/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrecklerMonitorTabPanel.java
 *
 * Created on Mar 13, 2010, 9:18:12 PM
 */

package org.freckler.gui.photo;

import org.freckler.gui.browse.FriendBrowserPanel;

/**
 *
 * @author humankind
 */
public class FrecklerMonitorTabPanel extends javax.swing.JPanel {

    /** Creates new form FrecklerMonitorTabPanel */
    public FrecklerMonitorTabPanel() {
        initComponents();
    }
	public ImageDisplayPanel getStatusPanel() {
		return tab_Status;
	}
	public MultiPhotoPanel getMultiPhotoPanel() {
		return tab_Photos;
	}
	public FriendBrowserPanel getBrowserPanel() {
		return tab_Browser;
	}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab_Photos = new org.freckler.gui.photo.MultiPhotoPanel();
        tab_Status = new org.freckler.gui.photo.ImageDisplayPanel();
        tab_Browser = new org.freckler.gui.browse.FriendBrowserPanel();

        jTabbedPane1.addTab("photos", tab_Photos);

        javax.swing.GroupLayout tab_StatusLayout = new javax.swing.GroupLayout(tab_Status);
        tab_Status.setLayout(tab_StatusLayout);
        tab_StatusLayout.setHorizontalGroup(
            tab_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        tab_StatusLayout.setVerticalGroup(
            tab_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("status", tab_Status);
        jTabbedPane1.addTab("browser", tab_Browser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.freckler.gui.browse.FriendBrowserPanel tab_Browser;
    private org.freckler.gui.photo.MultiPhotoPanel tab_Photos;
    private org.freckler.gui.photo.ImageDisplayPanel tab_Status;
    // End of variables declaration//GEN-END:variables

}
