/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MultiPhotoPanel.java
 *
 * Created on Mar 14, 2010, 11:44:14 AM
 */

package org.freckler.gui.photo;


import org.freckler.extra.FreckbaseFacade;

/**
 *
 * @author humankind
 */
public class MultiPhotoPanel extends javax.swing.JPanel {

    /** Creates new form MultiPhotoPanel */
    public MultiPhotoPanel() {
        initComponents();
    }
	public void setFreckbaseFacade(FreckbaseFacade ff) {
		photoMonitorPanel_1.setFreckbaseFacade(ff);
		photoMonitorPanel_2.setFreckbaseFacade(ff);
	}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        photoMonitorPanel_1 = new org.freckler.gui.photo.PhotoMonitorPanel();
        photoMonitorPanel_2 = new org.freckler.gui.photo.PhotoMonitorPanel();

        jSplitPane1.setLeftComponent(photoMonitorPanel_1);
        jSplitPane1.setRightComponent(photoMonitorPanel_2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private org.freckler.gui.photo.PhotoMonitorPanel photoMonitorPanel_1;
    private org.freckler.gui.photo.PhotoMonitorPanel photoMonitorPanel_2;
    // End of variables declaration//GEN-END:variables

}
