/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FriendBrowserPanel.java
 *
 * Created on Jun 19, 2010, 8:35:50 PM
 */

package org.freckler.gui.browse;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author humankind
 */
public class FriendBrowserPanel extends javax.swing.JPanel {

	FriendBrowserImpl	myFBI;
    /** Creates new form FriendBrowserPanel */
    public FriendBrowserPanel() {
        initComponents();
		myFBI = new FriendBrowserImpl();
		myFBI.registerStatusLabels(lab_friendOpStat, lab_photoOpStatus);
		myFBI.initTables(friendTable, entryTable);
    }
	public FriendBrowserImpl getBrowserImpl() {
		return myFBI;
	}
	private File chooseImageFile() {
		JFileChooser chooser = new JFileChooser();
		FileNameExtensionFilter filter = new FileNameExtensionFilter(
			"JPG & GIF Images", "jpg", "gif", "bmp", "png");
		chooser.setFileFilter(filter);
		int returnVal = chooser.showOpenDialog(this);
		File selectedFile = null;
		if(returnVal == JFileChooser.APPROVE_OPTION) {
			selectedFile = chooser.getSelectedFile();
			System.out.println("User selected photo image: " + selectedFile);
		}
		return selectedFile;
	}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitFriendsAndPhotos = new javax.swing.JSplitPane();
        friendBrowsingPanel = new javax.swing.JPanel();
        friendTableScrollPane = new javax.swing.JScrollPane();
        friendTable = new javax.swing.JTable();
        friendButtonPanel = new javax.swing.JPanel();
        but_removeFriend = new javax.swing.JButton();
        txt_friendName = new javax.swing.JTextField();
        but_addFriend = new javax.swing.JButton();
        lab_friendName = new javax.swing.JLabel();
        but_setFriendName = new javax.swing.JButton();
        lab_friendOpStat = new javax.swing.JLabel();
        check_autoEnroll = new javax.swing.JCheckBox();
        photoBrowsingPanel = new javax.swing.JPanel();
        entryButtonPanel = new javax.swing.JPanel();
        but_addPhoto = new javax.swing.JButton();
        but_removePhoto = new javax.swing.JButton();
        lab_photoOpStatus = new javax.swing.JLabel();
        entryTableScrollPane = new javax.swing.JScrollPane();
        entryTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        splitFriendsAndPhotos.setDividerLocation(200);
        splitFriendsAndPhotos.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        friendBrowsingPanel.setLayout(new java.awt.BorderLayout());

        friendTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        friendTableScrollPane.setViewportView(friendTable);

        friendBrowsingPanel.add(friendTableScrollPane, java.awt.BorderLayout.CENTER);

        but_removeFriend.setText("remove friend");
        but_removeFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_removeFriendActionPerformed(evt);
            }
        });

        txt_friendName.setText("amigo");
        txt_friendName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_friendNameActionPerformed(evt);
            }
        });

        but_addFriend.setText("add friend");
        but_addFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_addFriendActionPerformed(evt);
            }
        });

        lab_friendName.setText("new name");

        but_setFriendName.setText("set name");
        but_setFriendName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_setFriendNameActionPerformed(evt);
            }
        });

        lab_friendOpStat.setBackground(new java.awt.Color(255, 255, 255));
        lab_friendOpStat.setText("status: browsing");
        lab_friendOpStat.setOpaque(true);

        check_autoEnroll.setText("auto enroll from query images");
        check_autoEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_autoEnrollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout friendButtonPanelLayout = new javax.swing.GroupLayout(friendButtonPanel);
        friendButtonPanel.setLayout(friendButtonPanelLayout);
        friendButtonPanelLayout.setHorizontalGroup(
            friendButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(friendButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(friendButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(friendButtonPanelLayout.createSequentialGroup()
                        .addComponent(but_addFriend)
                        .addGap(18, 18, 18)
                        .addComponent(but_removeFriend)
                        .addGap(18, 18, 18)
                        .addComponent(lab_friendOpStat, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(check_autoEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(friendButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(friendButtonPanelLayout.createSequentialGroup()
                        .addComponent(txt_friendName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(but_setFriendName))
                    .addComponent(lab_friendName))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        friendButtonPanelLayout.setVerticalGroup(
            friendButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(friendButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(friendButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(friendButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, friendButtonPanelLayout.createSequentialGroup()
                            .addComponent(lab_friendName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_friendName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(but_setFriendName, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(friendButtonPanelLayout.createSequentialGroup()
                        .addGroup(friendButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(but_addFriend)
                            .addComponent(but_removeFriend)
                            .addComponent(lab_friendOpStat, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_autoEnroll)))
                .addContainerGap())
        );

        friendBrowsingPanel.add(friendButtonPanel, java.awt.BorderLayout.PAGE_END);

        splitFriendsAndPhotos.setTopComponent(friendBrowsingPanel);

        photoBrowsingPanel.setLayout(new java.awt.BorderLayout());

        but_addPhoto.setText("add profile entry");
        but_addPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_addPhotoActionPerformed(evt);
            }
        });

        but_removePhoto.setText("remove profile entry");
        but_removePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_removePhotoActionPerformed(evt);
            }
        });

        lab_photoOpStatus.setText("status: browsing");

        javax.swing.GroupLayout entryButtonPanelLayout = new javax.swing.GroupLayout(entryButtonPanel);
        entryButtonPanel.setLayout(entryButtonPanelLayout);
        entryButtonPanelLayout.setHorizontalGroup(
            entryButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryButtonPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(but_addPhoto)
                .addGap(27, 27, 27)
                .addComponent(but_removePhoto)
                .addGap(41, 41, 41)
                .addComponent(lab_photoOpStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        entryButtonPanelLayout.setVerticalGroup(
            entryButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(entryButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_addPhoto)
                    .addComponent(but_removePhoto)
                    .addComponent(lab_photoOpStatus))
                .addContainerGap())
        );

        photoBrowsingPanel.add(entryButtonPanel, java.awt.BorderLayout.SOUTH);

        entryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        entryTable.setRowHeight(40);
        entryTableScrollPane.setViewportView(entryTable);

        photoBrowsingPanel.add(entryTableScrollPane, java.awt.BorderLayout.CENTER);

        splitFriendsAndPhotos.setRightComponent(photoBrowsingPanel);

        add(splitFriendsAndPhotos, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	private void but_removeFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_removeFriendActionPerformed
		FriendBrowserImpl.FriendStat stat = getSelectedFriendStat();
		if (stat != null) {
			String title = "confirm friend deletion";
			String msg = "Are you sure you want to delete the friend with ID " + stat.ident
				+ " and name " + stat.name + "?";
			int selectedOption = JOptionPane.showConfirmDialog(this, msg, title,
					JOptionPane.YES_NO_OPTION);
			if (selectedOption == JOptionPane.YES_OPTION) {
				myFBI.removeFriend(stat.ident);
			}
		}
	}//GEN-LAST:event_but_removeFriendActionPerformed

	private void but_addFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_addFriendActionPerformed
		myFBI.setFriendOpStatus("status: selecting first photo for new friend");
		File imageFile = chooseImageFile();
		if (imageFile != null) {
			Long friendID = myFBI.makeNewFriend(imageFile);
			if (friendID != null) {
				myFBI.setFriendOpStatus("status: created new friend with ID=" + friendID);
				// TODO: Force new friend row to be selected in table
			}
		} else {
			myFBI.setFriendOpStatus("status: no photo selected for new friend");
		}
	}//GEN-LAST:event_but_addFriendActionPerformed

	private void txt_friendNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_friendNameActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txt_friendNameActionPerformed
	private FriendBrowserImpl.FriendStat getSelectedFriendStat() {
		FriendBrowserImpl.FriendStat stat = null;
		int selectedRow = friendTable.getSelectedRow();
		if (selectedRow >= 0) {
			stat = myFBI.getFriendStatForTableRow(selectedRow);
		}
		return stat;
	}
	private void but_setFriendNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_setFriendNameActionPerformed
		String newName = txt_friendName.getText();
		int selectedRow = friendTable.getSelectedRow();
		if ((selectedRow != -1) && (newName.length() > 0)) {
			myFBI.setFriendName(selectedRow, newName);
		}
	}//GEN-LAST:event_but_setFriendNameActionPerformed

	private void but_addPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_addPhotoActionPerformed
		myFBI.setEntryOpStatus("status: selecting new photo for old friend");
		FriendBrowserImpl.FriendStat fstat = getSelectedFriendStat();
		File imageFile = chooseImageFile();
		if ((fstat != null) && (imageFile != null)) {
			myFBI.addPhotoToFriendProfile(fstat.ident, imageFile);
		}

//		if (!success) {
//			lab_status.setText("Failed to expand friend '" + friendIdentText + "'");
//		}
	}//GEN-LAST:event_but_addPhotoActionPerformed

	private void but_removePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_removePhotoActionPerformed
		int selectedEntryRow =  entryTable.getSelectedRow();
		if (selectedEntryRow >= 0) {
			Long entryID = myFBI.getProfileEntryID_forRow(selectedEntryRow);
			String title = "confirm entry deletion";
			String msg = "Are you sure you want to delete the profile entry with ID " + entryID +" ?";
			int selectedOption = JOptionPane.showConfirmDialog(this, msg, title,
					JOptionPane.YES_NO_OPTION);
			if (selectedOption == JOptionPane.YES_OPTION) {
				myFBI.removeProfileEntry(entryID);
			}

		}
	}//GEN-LAST:event_but_removePhotoActionPerformed

	private void check_autoEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_autoEnrollActionPerformed
		boolean autoEnroll = check_autoEnroll.isSelected();
		myFBI.setAutoEnrollFlag(autoEnroll);
	}//GEN-LAST:event_check_autoEnrollActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_addFriend;
    private javax.swing.JButton but_addPhoto;
    private javax.swing.JButton but_removeFriend;
    private javax.swing.JButton but_removePhoto;
    private javax.swing.JButton but_setFriendName;
    private javax.swing.JCheckBox check_autoEnroll;
    private javax.swing.JPanel entryButtonPanel;
    private javax.swing.JTable entryTable;
    private javax.swing.JScrollPane entryTableScrollPane;
    private javax.swing.JPanel friendBrowsingPanel;
    private javax.swing.JPanel friendButtonPanel;
    private javax.swing.JTable friendTable;
    private javax.swing.JScrollPane friendTableScrollPane;
    private javax.swing.JLabel lab_friendName;
    private javax.swing.JLabel lab_friendOpStat;
    private javax.swing.JLabel lab_photoOpStatus;
    private javax.swing.JPanel photoBrowsingPanel;
    private javax.swing.JSplitPane splitFriendsAndPhotos;
    private javax.swing.JTextField txt_friendName;
    // End of variables declaration//GEN-END:variables

}
